"""
Django settings for midi_style_transfer project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lxr=-&^*@_(c*s9x4jvjl3$$xgt-4r6285q4(ryd1mi0vne5wn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['http://localhost:3000', '127.0.0.1', '']
#ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'firstapp.apps.FirstappConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]

ROOT_URLCONF = 'midi_harmony_transfer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "django.core.context_processors.media"
            ],
        },
    },
]
SETTINGS_PATH = r"E:\Onedrive\OneDrive - pinschoolo.pinschoolo\coding_projects\midi_harmony_transfer\reactapp\public"
TEMPLATE_DIRS = (
    os.path.join(SETTINGS_PATH, 'templates'),
)

#MEDIA_ROOT = os.path.join(BASE_DIR, 'data/') # 'data' is my media folder
#MEDIA_URL = '/media/'

WSGI_APPLICATION = 'midi_harmony_transfer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
'''
DATABASES = {
'default': {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
 }
}
'''

DATABASES = {
   'default': {
    'ENGINE': 'mssql',
    'HOST': "DESKTOP-LOONG\SQLEXPRESS",
    'USER': "DESKTOP-LOONG\loong",
    'PASSWORD': "",
    'NAME': "",
    'PORT': "1433",
    'OPTIONS': {
    'driver' : 'ODBC Driver 17 for SQL Server'
        },
    }
}

#Azure SQL
'''
DATABASES = {
   'default': {
    'ENGINE': 'mssql',
    'HOST': "tcp:midisqlserver.database.windows.net",
    'USER': "azureuser@midisqlserver",
    'PASSWORD': "878B50e56",
    'NAME': "midi_data",
    'PORT': "",
    'OPTIONS': {
    'driver' : 'ODBC Driver 17 for SQL Server'
        },
    }
}
'''
# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS_ORIGIN_WHITELIST = (
#     'http://localhost:3000/api/'

# )
CSRF_TRUSTED_ORIGINS = ['http://localhost:3000']

CSRF_COOKIE_SECURE = False

CORS_ORIGIN_ALLOW_ALL=True
CSRF_COOKIE_HTTPONLY = False